name: sitama3
description: Magang Sitama

# Versi Flutter yang digunakan
environment:
  sdk: '>=3.3.3 <4.0.0'

# Dependencies
dependencies:
    flutter:
        sdk: flutter
    google_fonts: ^4.0.3
    cupertino_icons: ^1.0.6
    flutter_svg: ^1.0.0
    intl:
    flutter_bloc:
    dio:
    get_it:
    dartz:
    logger:
    shared_preferences:

# Dev dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# Flutter specific configurations
flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/images/sitama_logo.png
    - assets/images/google_logo.png
    - assets/images/logo.png
    - assets/images/home_pattern.png
    - assets/images/loginIlustration.png
    - assets/images/pattern.png
    - assets/vectors/google.svg
    - assets/vectors/login_vektor.svg